apply plugin: "com.android.application"

android {
    namespace "com.xiaonan.lovepage"
    compileSdk 34

    defaultConfig {
        applicationId "com.xiaonan.lovepage"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

}

dependencies {
}
